### ISSUE TITLE
Implement api_key

### ISSUE THREAD

**Issue by zmallen** [zmallen/pygraylog#5]
API calls can also use API keys.

We have the instance variable `api_key` but dont do anything with it..
If not `None`, Use `api_key`, even if `username` and `password` are also not `None`

**Comment by jafferli** [comment]
I have issue a pull request to support that api_key implementation. please give a feedback.

**Comment by zmallen** [comment]
#8 reference

**Comment by zmallen** [comment]
Done with #8 !
